trigger: none
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - .gitignore/*

parameters:
  - name: DOCKER_BUILD_IMAGE
    displayName: Docker Image
    type: string
    default: 'openjdk:17-oracle'

  - name: PET_CLINIC_APP
    displayName: Pet Clinic App
    type: object
    default:
    - name: Pet_App
      build:
        docker_image: default_image  

resources:
  containers:
  - container: default image
    image: ${{ parameters.DOCKER_BUILD_IMAGE }}

variables:
- name: default_pool
  value: Default

stages:
- template: ../lib/app/stages/build/build.yml    