trigger: none
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - .gitignore/*

parameters:
  - name: DOCKER_BUILD_IMAGE
    displayName: Docker Image
    type: string
    default: 'openjdk:17-oracle'

resources:
  containers:
  - container: default image
    image: ${{ parameters.DOCKER_BUILD_IMAGE }}

stages:
- template: ../lib/app/stages/build/build.yml    